/* Automatically generated by dapto: DO NOT EDIT */

#ifndef envmod_DAPTO_H
#define envmod_DAPTO_H
#include "dapto.h"
#include "eliproto.h"
#include "envmod.h"
extern void _dap_envmod_init ();
#ifdef PROTO_OK
extern void _dapto_env_created (Environment, Environment);
#else
extern void _dapto_env_created ();
#endif
#ifdef PROTO_OK
extern void _dapto_binding_made (Environment, int, DefTableKey);
#else
extern void _dapto_binding_made ();
#endif
#endif
