/* Automatically generated by dapto: DO NOT EDIT */

#ifndef csm_DAPTO_H
#define csm_DAPTO_H
#include "dapto.h"
#include "eliproto.h"
#include <stdlib.h>
#include <string.h>
#include "csm.h"
extern void _dap_csm_init ();
#ifdef PROTO_OK
extern void _dapto_string_stored (int, const char *);
#else
extern void _dapto_string_stored ();
#endif
#endif
