
/* mapping of RULEcodes to visit procedures */

#include "visitprocs.h"

#include "visitmap.h"

_VPROCPTR VS1MAP[] = {
(_VPROCPTR)_VS1START, (_VPROCPTR)_VS1OPTIONS1, (_VPROCPTR)_VS1OPTIONS2, (_VPROCPTR)_VS1OPTEXP, 
(_VPROCPTR)_VS1OPTORD, (_VPROCPTR)_VS1OPTOPT, (_VPROCPTR)_VS1OPTBACK, (_VPROCPTR)_VS1IDENTS1, (_VPROCPTR)_VS1IDENTS2, 
(_VPROCPTR)_VS1EXPANDS1, (_VPROCPTR)_VS1EXPANDS2, (_VPROCPTR)_VS1ORDERS1, (_VPROCPTR)_VS1ORDERS2, (_VPROCPTR)_VS1OPTIMS1, 
(_VPROCPTR)_VS1OPTIMS2, (_VPROCPTR)_VS1BACKS1, (_VPROCPTR)_VS1BACKS2, (_VPROCPTR)_VS1EXPAND1, (_VPROCPTR)_VS1EXPAND3, 
(_VPROCPTR)_VS1EXPAND2, (_VPROCPTR)_VS1ORDER1, (_VPROCPTR)_VS1ORDER2, (_VPROCPTR)_VS1ORDER3, (_VPROCPTR)_VS1ORDER4, 
(_VPROCPTR)_VS1ARRANGE1, (_VPROCPTR)_VS1ARRANGE4, (_VPROCPTR)_VS1ARRANGE2, (_VPROCPTR)_VS1ARRANGE3, (_VPROCPTR)_VS1ATTR1, 
(_VPROCPTR)_VS1OPTIM1, (_VPROCPTR)_VS1OPTIM2, (_VPROCPTR)_VS1OPTIM3, (_VPROCPTR)_VS1ATTRTYPE1, (_VPROCPTR)_VS1ATTRTYPE2, 
(_VPROCPTR)_VS1ATTRS1, (_VPROCPTR)_VS1ATTRS2, (_VPROCPTR)_VS1ATTRNAMES, (_VPROCPTR)_VS1NAMESL1, (_VPROCPTR)_VS1NAMESL2, 
(_VPROCPTR)_VS1BACKEND1, (_VPROCPTR)_VS1BACKEND2
};
