/* Automatically generated by dapto: DO NOT EDIT */

#ifndef dapto_DAPTO_H
#define dapto_DAPTO_H
#include "dapto.h"
#include "eliproto.h"
extern void _dap_dapto_init ();
#ifdef PROTO_OK
extern void _dapto_init (int);
#else
extern void _dapto_init ();
#endif
#ifdef PROTO_OK
extern void _dapto_finit ();
#else
extern void _dapto_finit ();
#endif
#ifdef PROTO_OK
extern void _dapto_exit ();
#else
extern void _dapto_exit ();
#endif
#ifdef PROTO_OK
extern void _dapto_stopped (CONST char *, int);
#else
extern void _dapto_stopped ();
#endif
#ifdef PROTO_OK
extern void _dapto_enter (CONST char *);
#else
extern void _dapto_enter ();
#endif
#ifdef PROTO_OK
extern void _dapto_leave (CONST char *);
#else
extern void _dapto_leave ();
#endif
#endif
