
PreDefSymKey ("NODEPTR", NODEPTRsym, NODEPTRkey)
PreDefSymKey ("POSITION", POSITIONsym, POSITIONkey)
PreDefSymKey ("$SYMB", SYMBsym, SYMBkey)
PreDefSymKey ("$BOOL", BOOLsym, BOOLkey)
PreDefSymKey ("int", intsym, intkey)
PreDefSymKey ("$VOID_LIST", VOID_LISTsym, VOID_LISTkey)
PreDefSymKey ("VOID", VOIDsym, VOIDkey)

PreDefSymKey ("ROOTCLASS", ROOTCLASSsym, ROOTCLASSkey)
PreDefSymKey ("NULLNODEPTR", NULLNODEPTRsym, NULLNODEPTRkey)
PreDefSym ("GENTREE", GENTREEsym)
PreDefSymKey ("IF", IFsym, IFkey)
PreDefSymKey ("ORDER", ORDERsym, ORDERkey)
PreDefSymKey ("RuleFct", RuleFctsym, RuleFctkey)
PreDefSymKey ("RhsFct", RhsFctsym, RhsFctkey)
PreDefSymKey ("TermFct", TermFctsym, TermFctkey)
PreDefSymKey ("LINE", LINEsym, LINEkey)
PreDefSymKey ("COL", COLsym, COLkey)
PreDefSymKey ("COORDREF", COORDREFsym, COORDREFkey)
PreDefSymKey ("RULENAME", RULENAMEsym, RULENAMEkey)
