
/* mapping of RULEcodes to visit procedures */

#include "visitprocs.h"

#include "visitmap.h"

_VPROCPTR VS1MAP[] = {
(_VPROCPTR)_VS1Root, (_VPROCPTR)_VS1Opt1, (_VPROCPTR)_VS1Opt2, (_VPROCPTR)_VS1Opt3, 
(_VPROCPTR)_VS1Opt4, (_VPROCPTR)_VS1Opt5, (_VPROCPTR)_VS1F1, (_VPROCPTR)_VS1F2, (_VPROCPTR)_VS1F3, 
(_VPROCPTR)_VS1T1, (_VPROCPTR)_VS1T2, (_VPROCPTR)_VS1T3, (_VPROCPTR)_VS1M1, (_VPROCPTR)_VS1M2, 
(_VPROCPTR)_VS1M3, (_VPROCPTR)_VS1M4, (_VPROCPTR)_VS1M5, (_VPROCPTR)_VS1M6, (_VPROCPTR)_VS1M7, 
(_VPROCPTR)_VS1M8, (_VPROCPTR)_VS1D1, (_VPROCPTR)_VS1D2, (_VPROCPTR)_VS1D3, (_VPROCPTR)_VS1DS1, 
(_VPROCPTR)_VS1DS2, (_VPROCPTR)_VS1DS3, (_VPROCPTR)_VS1DS4, (_VPROCPTR)_VS1DS5, (_VPROCPTR)_VS1DS6, 
(_VPROCPTR)_VS1DC1, (_VPROCPTR)_VS1DC2, (_VPROCPTR)_VS1DC3, (_VPROCPTR)_VS1DC4, (_VPROCPTR)_VS1DC5, 
(_VPROCPTR)_VS1DC6, (_VPROCPTR)_VS1DC7, (_VPROCPTR)_VS1DC8, (_VPROCPTR)_VS1DC9, (_VPROCPTR)_VS1DC10, 
(_VPROCPTR)_VS1DC11, (_VPROCPTR)_VS1DE1, (_VPROCPTR)_VS1DE2, (_VPROCPTR)_VS1DE3, (_VPROCPTR)_VS1SW1, 
(_VPROCPTR)_VS1SW2
};
